import yolo from "../assets/img/logo/yolo.png";
import obs from "../assets/img/logo/obs.png";
import mediapipe from "../assets/img/logo/mediapipe.png";
import zmq from "../assets/img/logo/zmq.png";
import pygame from "../assets/img/logo/pygame.png";


import img0 from "../assets/projects/thumbnails/portfolio.png"
import img1 from "../assets/projects/thumbnails/image_processing_gui.png"
import img2 from "../assets/projects/thumbnails/infinite_virtual_web_loop.png"
import img3 from "../assets/projects/thumbnails/dbm_simulation.png"
import img4 from "../assets/projects/thumbnails/reinforcemenet_learning.png"
import img5 from "../assets/projects/thumbnails/banana-room.png"


const devicon = "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/"

const projects = [
    {
        name: "Project 0",
        description: "Personal Portfolio",
        link: "https://github.com/kayeungadrian-tam/Image_Processing",
        img: img0,
        tags: ["Python", "OpenCV", "PysimpleGUI", "Yolov3"],
        icons: [
            devicon + "/vuejs/vuejs-original.svg",
            devicon + "typescript/typescript-original.svg",
            "https://karmanivero.us/assets/images/vercel-logo.png"
        ],
        overview:
            "A personal porfolio website made from scratch in Vue3 with ts. UI components are mostly done using ElementPlus. The website is hosted by Vercel.",
    },

    {
        name: "Project 1",
        description: "Image Processing GUI",
        link: "https://github.com/kayeungadrian-tam/Image_Processing",
        img: img1,
        tags: ["Python", "OpenCV", "PysimpleGUI", "Yolov3"],
        icons: [
            devicon + "/python/python-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/opencv/opencv-original.svg",
            yolo

        ],
        overview:
            "A GUI for image processing using OpenCV, PySimpleGUI and Yolov3. It aims to provide a way to test the object detection model on preprocessed image in real time.  ",
    },
    {
        name: "Project 2",
        description: "Infinite Virtual Webcam Loop",
        link: "https://github.com/kayeungadrian-tam/Infinite-Meeting",
        img: img2,
        tags: ["Python", "OpenCV", "Mediapipe", "OBS"],
        icons: [
            devicon + "/python/python-original.svg",
            "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/opencv/opencv-original.svg",
            obs,
            mediapipe

        ],
        overview:
            "A virtual webcam loop using OpenCV, Mediapipe and OBS. A simple program to record a video from a webcam and play it on repeat. It then sends the video to OBS for streaming.",
    },
    {
        name: "Project 3",
        description: "Dynamics Bicycle Model Simulation",
        link: "https://github.com/kayeungadrian-tam/Dynamics_Bicycle_Model",
        img: img3,
        tags: ["Python", "Dash", "PID", "Sim", "ZMQ"],
        icons: [
            devicon + "/python/python-original.svg",
            devicon + "flask/flask-original.svg",
            zmq
        ],
        overview:
            "A 3D simulation of dynamic bicycle model with PID control, where all the data generated by the model are viewable on a web server in real-time.",
    },
    {
        name: "Project 4",
        description: "Reinforcement Learning PoC",
        link: "https://github.com/kayeungadrian-tam/Reinforcement_Learning",
        img: img4,
        tags: ["Tensorflow", "PyGame", "OpenAI", "RL"],
        icons: [
            devicon + "python/python-original.svg",
            pygame,
            devicon + "tensorflow/tensorflow-original.svg",

        ],
        overview:
            "A PoC project to apply reinforcement learning algorithm to autonomous driving which include obstacles avoidance and object pursuit.",
    },
    {
        name: "Project 5",
        description: "Mobile Application",
        link: "https://github.com/kayeungadrian-tam/The-Banana-Room",
        img: img5,
        tags: ["Vue3", "Js", "FastAPI", "Docker"],
        icons: [
            devicon + "flutter/flutter-original.svg",
            devicon + "dart/dart-original.svg",
            devicon + "firebase/firebase-plain.svg"

        ],
        overview: "A general puroposed mobile application that includes a real-time chatroom, a customizable user profile and a simple puzzle game.",
    }
]



export default projects;